name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to dockerhub
      run: docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build
      
    - name: Push the Docker image
      run: docker compose push
