version: "1.0"
services:
  mock-mddsz-frontend:
    build: ./frontend/
    image: hktari/asistent-logging:mock-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT}
      - REACT_APP_BACKEND_HOST=mock-mddsz-backend
  mock-mddsz-backend:
    build: ./backend/
    image: hktari/asistent-logging:mock-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - HOST=${BACKEND_LISTEN_INTERFACE}
      - PORT=${BACKEND_PORT}